pipeline {
    agent any

    stages {

        stage('Clone Repo') {
            steps {
                echo 'Repository ready'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("lab6-backend", "Backend")
                }
            }
        }

        stage('Run Container') {
            steps {
                script {
                    docker.image("lab6-backend").run()
                }
            }
        }

    }
}